### ISSUE TITLE
How to setup autoprefixer

### ISSUE THREAD

**Issue by norixx** [kiennp/web-assets-compiler#2]
Hi. Quick question.
How can i use Autoprefixer setting in the extension? Should it be in settings.json?
So far I set like this.

```
"webAssetsCompiler.targetFolders": [
    {
      "input": "",
      "excludePattern" : "_.+\\.scss",
      "browserslist": [
        "defaults"
      ]
    }
  ],
```
I cannot tell if it's working.
Please advise.

**Comment by kiennp** [comment]
You can add `.browserslistrc` to your project's root directory.
See more at https://github.com/browserslist/browserslist#queries

**Comment by norixx** [comment]
@kiennp Great. It worked! thanks
